name: "test github action"

on:
  workflow_dispatch:
  push:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: pre
        run: |
          echo "ids=$(awk 'BEGIN {for (i=1;i<=100;i++) print i}')" >>$GITHUB_ENV
          export "ids=$(awk 'BEGIN {for (i=1;i<=100;i++) print i}')"
          echo "toJSON($ids)"

  test:
    needs:
      - pre
    strategy:
      fail-fast: true
      matrix:
        no: ${{ needs.pre.env.ids }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run script
      run: scripts/run.sh
    - name: Run script
      if: ${{ env.UPLOAD_IMAGE == 'YES' }}
      run: echo "2333"
