name: "test github action"

on:
  workflow_dispatch:
  push:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: pre
        run: |
          abcd=({1..1000})
          string=$(IFS=,; echo "${abcd[*]}") 
          string=${string//,/ }
          string="[$string]"
          echo "ids=${string}" >>$GITHUB_ENV
          echo ${{ toJSON( env.ids ) }}

  test:
    needs:
      - pre
    strategy:
      fail-fast: true
      matrix:
        no: ${{ needs.pre.env.ids }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run script
      run: scripts/run.sh
    - name: Run script
      if: ${{ env.UPLOAD_IMAGE == 'YES' }}
      run: echo "2333"
