name: "test github action"

on:
  workflow_dispatch:
  push:

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      output_id: ${{ steps.pre.outputs.ids }}
      output_id1: ${{ steps.pre.outputs.test }}
    steps:
      - name: pre
        id: pre
        run: |
          abcd=({1..1000})
          string=$(IFS=,; echo "${abcd[*]}") 
          #string=${string//,/ }
          string="[$string]"
          echo "ids=${string}" >>"$GITHUB_OUTPUT"
          echo "test=world" >> "$GITHUB_OUTPUT"
#          echo ${{ toJSON( env.ids ) }}

  test:
    needs:
      - pre
    strategy:
      fail-fast: true
      matrix:
        no: ${{ toJSON(needs.pre.outputs.output_id) }}
    runs-on: ubuntu-latest
    env:
      OUTPUT1: ${{needs.pre.outputs.output_id}}
      OUTPUT2: ${{needs.pre.outputs.output_id1}}
    steps:
    - name: abc
      run: |
        echo "${{ env.OUTPUT1 }}"
        echo "${{ env.OUTPUT2 }}"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run script
      run: scripts/run.sh
    - name: Run script
      if: ${{ env.UPLOAD_IMAGE == 'YES' }}
      run: echo "2333"
